# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_domain_redirect" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_ec2_ebs_docker_host" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_lambda_api" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_lambda_cronjob" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_mailgun_domain" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_reverse_proxy" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_static_site" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/aws_vpc_msk" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/static_website_ssl_cloudfront_private_s3" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws/wordpress_fargate" # Location of package manifests
    schedule:
      interval: "weekly"
